import styles from '@/styles/Home.module.css'
import { Inter } from '@next/font/google'
import Head from 'next/head'

import dynamic from 'next/dynamic';

const ReactQuillEditor = dynamic(() => import('@/components/react-quill-editor'), {
  ssr: false,
})

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Simple example of using react-quill with Next.js and TypeScript.
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              BostonLeeK
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.form}>
            <ReactQuillEditor />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/BostonLeeK"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              My Account
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
